version: "3.8"

services:

  postgres:
    image: postgres:12.12-alpine3.16
    ports:
      - ${POSTGRES_PORT:-6432:5432}
    environment:
      POSTGRES_DB: perfberry
      POSTGRES_USER: perfberry
      POSTGRES_PASSWORD: secret

  api:
    image: 2gistestlabs/perfberry-api
    ports:
      - 9000:9000
    depends_on:
      - postgres

  ui:
    image: 2gistestlabs/perfberry-ui
    ports:
      - 3000:3000
    depends_on:
      - api

  cli:
    image: 2gistestlabs/perfberry-cli
    volumes:
      - ./example:/example:ro
