name: Publish perfberry-api

on:
  push:
    tags:
      - '*'

jobs:
  publish_docker_hub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Inspect Builder
      run: docker buildx inspect

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: perfberry
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: perfberry-api/
        push: true
        tags: perfberry/perfberry-api
        platforms: linux/amd64
